### ISSUE TITLE
blogUrl-404

### ISSUE THREAD

**Issue by Jack-rainbow** [wx-chevalier/Awesome-CheatSheets#3]
**Page 404**

**目前行为**
url：https://wxyyxc1992.github.io/
problem：页面404

**预期行为**
url：https://wxyyxc1992.github.io/
我希望你可以blog修复404，我可以欣赏您blog，从而更新自己的技术栈。

**系统信息**
 - OS: Win10
 - Browser ：chrome
 - Version ：74

**其他**
感谢您的支持与理解，期待您的回复。~~~您的小迷弟

**Comment by wx-chevalier** [comment]
http://wx-chevalier.github.io
